# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JxCameraSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JxCameraSample
    pod 'JxCameraSDK', :git => 'https://github.com/JeilinDevelop/IOS-SDK.git'
    pod 'Alamofire', '~> 5.10.2'
    pod 'SnapKit'
    pod 'SwiftyJSON', '~> 5.0.2'
    pod 'Masonry', '~> 1.1.0'
    pod 'MJRefresh', '~> 3.7.9'
    pod 'MJExtension', '~> 3.4.2'
    pod 'Kingfisher', '~> 8.1.3'
    pod "FGRoute"
    pod 'Toast-Swift', '~> 5.1.1'

  target 'JxCameraSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JxCameraSampleUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
